# Generated by Django 4.2.7 on 2025-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
